version: '3'

services:
  webpack:
    image: node:11.7.0-alpine
    command: npm run start:js:dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8082:8082"

  server:
    build: .
    command: npm run start:server:dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - webpack
    environment:
      DEBUG: "smn*"
  
  postgres:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
